DEFAULT_BUTTON_PADDING = 5
DEFAULT_BOX_SPACING = 10

# Navigation constants
GO_BACK_KEYWORD = "go_back"
CHAMBRES = "CHAMBRES"
CHAMBRE_LIBRE = "CHAMBRE_LIBRE"
CHAMBRE_OCCUPEE = "CHAMBRE_OCCUPEE"
RESERVATIONS = "RESERVATIONS"
FACTURES = "FACTURES"
STATS = "STATS"
MAIN = "MAIN"
