DEFAULT_BUTTON_PADDING = 2
DEFAULT_BOX_SPACING = 10

# Navigation constants
GO_BACK_KEYWORD = "go_back"

CHAMBRES = "CHAMBRES"
CHAMBRE_LIBRE = "CHAMBRE_LIBRE"
CHAMBRE_OCCUPEE = "CHAMBRE_OCCUPEE"

RESERVATIONS = "RESERVATIONS"
VOIR_RESERVATIONS = "VOIR_RESERVATIONS"
AJOUTER_RESERVATION = "AJOUTER_RESERVATION"
SUPPRIMER_RESERVATION = "SUPPRIMER_RESERVATION"

FACTURES = "FACTURES"

STATS = "STATS"

MAIN = "MAIN"
