DEFAULT_BUTTON_PADDING = 5
DEFAULT_BOX_SPACING = 10

# Navigation constants
GO_BACK_KEYWORD = "go_back"
GESTION_HOTEL = "GESTION-HOTEL"
CHAMBRES = "CHAMBRES"
CLIENTS = "CLIENTS"
RESERVATIONS = "RESERVATIONS"
FACTURES = "FACTURES"
STATS = "STATS"